version: '3.1'
services:
  stats-server:
    build: ./statistics/stats-server
    image: stats-server_img
    container_name: stats-server_cont
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: postgres_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statistics
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - TZ="Etc/GMT-3"