DROP TABLE IF EXISTS endpointhits;

CREATE TABLE endpointhits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app varchar(255) NOT NULL,
  uri varchar(255) NOT NULL,
  ip varchar(255) NOT NULL,
  timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);