DROP FUNCTION IF EXISTS distance;
DROP TYPE IF EXISTS holder;
DROP TABLE IF EXISTS events_compilations;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS participation_requests;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS location_types;

CREATE type holder as (id bigint, dist float);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE location_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50),
    CONSTRAINT uq_location_type UNIQUE (name)
);

CREATE TABLE locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    radius FLOAT,
    name varchar(255),
    location_type_id bigint,
    CONSTRAINT uq_location_name UNIQUE (name),
    FOREIGN KEY (location_type_id) REFERENCES location_types(id)
);

CREATE TABLE events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation varchar(2000),
    category_id bigint,
    confirmed_requests bigint,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description varchar(7000),
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id bigint,
    location_id bigint,
    paid boolean,
    participant_limit bigint,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    request_moderation boolean,
    state varchar(255),
    title varchar(120),
    views bigint,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (initiator_id) REFERENCES users(id),
    FOREIGN KEY (location_id) REFERENCES locations(id)
);

CREATE TABLE participation_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITHOUT TIME ZONE,
    event bigint NOT NULL,
    requester bigint NOT NULL,
    status VARCHAR(255) NOT NULL,
    FOREIGN KEY (requester) REFERENCES users (id),
    FOREIGN KEY (event) REFERENCES events (id),
    CONSTRAINT uq_request UNIQUE (event, requester)
);

CREATE TABLE compilations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned boolean,
    title VARCHAR(50),
    CONSTRAINT uq_compilation_name UNIQUE (title)
);

CREATE TABLE events_compilations (
    event_id bigint,
    compilation_id bigint,
    FOREIGN KEY (event_id) REFERENCES events (id),
    FOREIGN KEY (compilation_id) REFERENCES compilations (id)
);

CREATE OR REPLACE FUNCTION distance(lat float, lon float, radius float) RETURNS holder[]
AS
'
DECLARE
	temprow record;
	tempholder holder;
	dists holder[] = ARRAY[]::holder[];
	dist float;
	rad_latRow float;
	rad_latInput float = pi() * lat / 180;
	theta float;
	rad_theta float;
	commonrad float;
BEGIN
	FOR temprow IN SELECT l.id,l.lat,l.lon,l.radius FROM locations as l
	LOOP
		rad_latRow = pi() * temprow.lat / 180;
		theta = lon - temprow.lon;
		rad_theta =  pi() * theta / 180;
		dist = sin(rad_latInput) * sin(rad_latRow) + cos(rad_latInput) * cos(rad_latRow) * cos(rad_theta);	
		IF dist > 1
            THEN dist = 1;
        END IF;
		dist = acos(dist);
		dist = dist * 180 / pi();
		dist = dist * 60 * 1.8524;
		
		IF dist < (radius + temprow.radius)
				THEN tempholder =  ROW(temprow.id, dist)::holder;
				dists = array_append(dists,tempholder);
		END IF;
	END LOOP;
	RETURN dists;
END;
'
LANGUAGE PLPGSQL;