DROP TABLE IF EXISTS events_compilations;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS participation_requests;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS locations;

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    CONSTRAINT uq_name UNIQUE (name)
);

CREATE TABLE locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation varchar(2000),
    category_id bigint,
    confirmed_requests bigint,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description varchar(7000),
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id bigint,
    location_id bigint,
    paid boolean,
    participant_limit bigint,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    request_moderation boolean,
    state varchar(255),
    title varchar(120),
    views bigint,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (initiator_id) REFERENCES users(id),
    FOREIGN KEY (location_id) REFERENCES locations(id)
);

CREATE TABLE participation_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITHOUT TIME ZONE,
    event bigint NOT NULL,
    requester bigint NOT NULL,
    status VARCHAR(255) NOT NULL,
    FOREIGN KEY (requester) REFERENCES users (id),
    FOREIGN KEY (event) REFERENCES events (id),
    CONSTRAINT uq_request UNIQUE (event, requester)
);

CREATE TABLE compilations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned boolean,
    title VARCHAR(50),
    CONSTRAINT uq_compilation_name UNIQUE (title)
);

CREATE TABLE events_compilations (
    event_id bigint,
    compilation_id bigint,
    FOREIGN KEY (event_id) REFERENCES events (id),
    FOREIGN KEY (compilation_id) REFERENCES compilations (id)
)